apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dsileecher-c322"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dsileecher-c322"
  template:
    metadata:
      labels:
        app: "dsileecher-c322"
    spec:
      containers:
        - name: "dsileecher-c322"
          image: "sdvfdb.azurecr.io/dsileecher"
          ports:
          - containerPort: 80