apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernates-23f4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernates-23f4"
  template:
    metadata:
      labels:
        app: "kubernates-23f4"
    spec:
      containers:
        - name: "kubernates-23f4"
          image: "rtuyjrj.azurecr.io/kubernates"
          ports:
          - containerPort: 80