apiVersion: v1
kind: Service
metadata:
    name: "kubernates-7a35"
    labels:
        app: "kubernates-7a35"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernates-7a35"