apiVersion: v1
kind: Service
metadata:
    name: "kubernates-23f4"
    labels:
        app: "kubernates-23f4"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernates-23f4"