apiVersion: v1
kind: Service
metadata:
    name: "kubernates-d164"
    labels:
        app: "kubernates-d164"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernates-d164"